title: Nirav Bariya
logo: /assets/images/profile_repo.png
description: This repository contains the presentation file and a detailed report on the analysis done for GameCo case study.
show_downloads: false
theme: jekyll-theme-minimal
